In [1]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings

# Important functionality for this lesson
from scipy import stats
import statsmodels.api as sm
import os

In [2]:
os.chdir("C:/Users/emshe/Desktop/BRAINSTATION/CAPSTONE/DATASETS")

In [21]:
van_rent_df = pd.read_csv("Vancouver_Historical_Average_Rents_by_Bedroom_Type.csv", skiprows = 2, nrows = 34, encoding = 'unicode_escape')
fairview_rent_df = pd.read_csv("South_Granville_Oak_Historical_Average_Rents_by_Bedroom_Type.csv", skiprows = 2, nrows = 15, encoding = 'unicode_escape')
van_vacancy_df = pd.read_csv("Vancouver_Historical_Vacancy_Rates_by_Bedroom_Type.csv", skiprows = 2, nrows = 35, encoding = 'unicode_escape')

In [22]:
display(van_vacancy_df)

,Unnamed: 0,Bachelor,Unnamed: 2,1 Bedroom,Unnamed: 4,2 Bedroom,Unnamed: 6,3 Bedroom +,Unnamed: 8,Total,Unnamed: 10,Unnamed: 11
0,1990 October,0.7,a,0.7,a,1.2,a,2.0,b,0.9,a,NaN
1,1991 October,1.8,b,2.1,a,2.6,a,1.6,a,2.2,a,NaN
2,1992 October,1.5,a,1.7,a,1.6,a,1.2,a,1.6,a,NaN
3,1993 October,0.7,a,1.1,a,1.2,a,1.6,a,1.1,a,NaN
4,1994 October,0.9,a,0.8,a,0.7,a,1.3,a,0.8,a,NaN
5,1995 October,0.6,a,1.2,a,1.3,a,1.1,a,1.2,a,NaN
6,1996 October,1.0,a,1.1,a,1.3,a,0.7,a,1.1,a,NaN
7,1997 October,1.9,b,1.6,a,1.6,a,2.8,c,1.7,a,NaN
8,1998 October,1.5,a,2.7,a,3.3,a,2.7,a,2.7,a,NaN
9,1999 October,1.9,a,2.8,a,2.5,a,2.6,a,2.6,a,NaN
10,2000 October,1.2,a,1.3,a,1.7,a,1.6,a,1.4,a,NaN
11,2001 October,1.1,a,1.0,a,1.0,a,1.0,a,1.0,a,NaN
12,2002 October,0.9,a,1.5,a,1.2,a,1.7,a,1.4,a,NaN
13,2003 October,1.5,a,2.1,a,2.1,a,1.8,a,2.0,a,NaN
14,2004 October,0.9,a,1.2,a,1.6,a,1.4,a,1.3,a,NaN
15,2005 October,1.0,a,1.2,a,1.9,a,2.0,a,1.4,a,NaN
16,2006 October,0.5,a,0.7,a,1.0,a,1.6,a,0.8,a,NaN
17,2007 October,0.5,a,0.7,a,1.0,a,1.4,a,0.8,a,NaN
18,2008 October,0.4,a,0.5,a,0.7,a,1.4,a,0.6,a,NaN
19,2009 October,1.4,a,2.1,a,2.6,a,3.9,a,2.2,a,NaN
20,2010 October,1.2,a,1.9,a,2.1,a,2.1,a,1.9,a,NaN
21,2011 October,0.9,a,1.4,a,1.5,a,2.2,a,1.4,a,NaN
22,2012 October,1.1,a,1.7,a,2.4,a,2.5,a,1.8,a,NaN
23,2013 October,1.1,a,1.6,a,1.9,a,2.4,a,1.7,a,NaN
24,2014 October,0.8,a,0.9,a,1.1,a,1.4,a,1.0,a,NaN
25,2015 October,0.6,a,0.8,a,0.9,a,1.4,a,0.8,a,NaN
26,2016 October,0.7,a,0.7,a,0.7,a,0.9,a,0.7,a,NaN
27,2017 October,0.8,a,0.9,a,1.0,a,1.3,a,0.9,a,NaN
28,2018 October,0.9,a,1.1,a,1.0,a,1.1,a,1.0,a,NaN
29,2019 October,0.7,a,1.0,a,1.5,a,1.3,a,1.1,a,NaN
30,2020 October,2.9,a,2.5,a,2.8,a,2.3,a,2.6,a,NaN
31,2021 October,1.4,a,1.1,a,1.3,a,1.6,a,1.2,a,NaN
32,2022 October,1.1,a,0.8,a,1.0,a,1.4,a,0.9,a,NaN
33,2023 October,0.9,a,0.8,a,1.1,a,1.0,a,0.9,a,NaN
34,2024 October,1.8,a,1.6,a,1.6,a,1.9,b,1.6,a,NaN